name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-20.04", "ubuntu-22.04"]

    name: "panda-model on ${{ matrix.os }} with Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Linux
        run: >
          sudo apt-get update && sudo apt-get install
          libpoco-dev
          libeigen3-dev
      - name: Build Python
        run: |
          python -m pip install --upgrade pip wheel
          pip install .
      - name: Build C++
        run: >
          mkdir build &&
          cd build &&
          cmake .. -DBUILD_CPP=ON &&
          cmake --build . &&
          cpack -G DEB
          
