name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: quay.io/pypa/manylinux2014_x86_64
    timeout-minutes: 100

    steps:
    - uses: actions/checkout@v3
    # - name: Set up Python
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.x'
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install build
    - name: Build package
      run: |
        /opt/python/cp37-cp37m/bin/python -m build .
        /opt/python/cp38-cp38/bin/python -m build .
        /opt/python/cp39-cp39/bin/python -m build .
        /opt/python/cp310-cp310/bin/python -m build .
        /opt/python/cp311-cp311/bin/python -m build .
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}